// Translation functionality
const translations = {
    en: {
        title: 'Birthday Wishlist Platform',
        subtitle: 'Create and share your wishlist with friends and family!',
        createWishlist: 'Create Your Wishlist',
        yourName: 'Your Name:',
        itemName: 'Item Name:',
        itemLink: 'Item Link (optional):',
        paste: 'Paste',
        price: 'Price (optional):',
        addItem: 'Add Item',
        loadingProduct: 'Loading product information...',
        yourCurrentWishlist: 'Your Current Wishlist',
        generateShareableLink: 'Generate Shareable Link',
        shareLinkText: 'Share this link with others:',
        copy: 'Copy',
        copied: 'Copied!',
        totalBudget: 'Total Budget',
        totalItems: 'Total Items',
        bookedItems: 'Booked Items',
        availableItems: 'Available Items',
        viewWishlist: 'View Someone\'s Wishlist',
        enterWishlistLink: 'Enter Wishlist Link:',
        loadWishlist: 'Load Wishlist',
        bookThisItem: 'Book this item',
        bookItem: 'Book Item',
        booked: 'Booked',
        bookedBy: 'Booked by:',
        viewItem: 'View Item',
        addToWishlist: 'Added to wishlist!',
        duplicateUrl: 'This URL is already in your wishlist!',
        shareableLinkGenerated: 'Shareable link generated! Send this to others.',
        wishlistOf: 'Wishlist of:',
        noItemsYet: 'No items yet',
        confirmBooking: 'Confirm Booking',
        yourNamePlaceholder: 'Your Name',
        welcomeMessage: 'Welcome to Birthday Wishlist!',
        welcomeDescription: 'Create your personal wishlist and share it with friends and family.',
        createButton: 'Create Your Wishlist'
    },
    uk: {
        title: 'Платформа списків бажань на день народження',
        subtitle: 'Створюйте та діліться своїм списком бажань з друзями та родиною!',
        createWishlist: 'Створити свій список бажань',
        yourName: 'Ваше ім\'я:',
        itemName: 'Назва товару:',
        itemLink: 'Посилання на товар (необов\'язково):',
        paste: 'Вставити',
        price: 'Ціна (необов\'язково):',
        addItem: 'Додати товар',
        loadingProduct: 'Завантаження інформації про товар...',
        yourCurrentWishlist: 'Ваш поточний список бажань',
        generateShareableLink: 'Згенерувати посилання для спільного доступу',
        shareLinkText: 'Поділіться цим посиланням з іншими:',
        copy: 'Копіювати',
        copied: 'Скопійовано!',
        totalBudget: 'Загальний бюджет',
        totalItems: 'Всього товарів',
        bookedItems: 'Заброньовані товари',
        availableItems: 'Доступні товари',
        viewWishlist: 'Переглянути чужий список бажань',
        enterWishlistLink: 'Введіть посилання на список бажань:',
        loadWishlist: 'Завантажити список бажань',
        bookThisItem: 'Забронювати цей товар',
        bookItem: 'Забронювати товар',
        booked: 'Заброньовано',
        bookedBy: 'Заброньовано:',
        viewItem: 'Переглянути товар',
        addToWishlist: 'Додано до списку бажань!',
        duplicateUrl: 'Це посилання вже є у вашому списку бажань!',
        shareableLinkGenerated: 'Посилання для спільного доступу згенеровано! Надішліть його іншим.',
        wishlistOf: 'Список бажань:',
        noItemsYet: 'Ще немає товарів',
        confirmBooking: 'Підтвердити бронювання',
        yourNamePlaceholder: 'Ваше ім\'я',
        welcomeMessage: 'Ласкаво просимо до Birthday Wishlist!',
        welcomeDescription: 'Створіть особистий список бажань та поділіться ним з друзями та родиною.',
        createButton: 'Створити свій список бажань'
    },
    ru: {
        title: 'Платформа списков желаний на день рождения',
        subtitle: 'Создавайте и делитесь своим списком желаний с друзьями и семьей!',
        createWishlist: 'Создать свой список желаний',
        yourName: 'Ваше имя:',
        itemName: 'Название товара:',
        itemLink: 'Ссылка на товар (необязательно):',
        paste: 'Вставить',
        price: 'Цена (необязательно):',
        addItem: 'Добавить товар',
        loadingProduct: 'Загрузка информации о товаре...',
        yourCurrentWishlist: 'Ваш текущий список желаний',
        generateShareableLink: 'Создать общую ссылку',
        shareLinkText: 'Поделитесь этой ссылкой с другими:',
        copy: 'Копировать',
        copied: 'Скопировано!',
        totalBudget: 'Общий бюджет',
        totalItems: 'Всего товаров',
        bookedItems: 'Забронированные товары',
        availableItems: 'Доступные товары',
        viewWishlist: 'Просмотреть чужой список желаний',
        enterWishlistLink: 'Введите ссылку на список желаний:',
        loadWishlist: 'Загрузить список желаний',
        bookThisItem: 'Забронировать этот товар',
        bookItem: 'Забронировать товар',
        booked: 'Забронировано',
        bookedBy: 'Забронировано:',
        viewItem: 'Просмотреть товар',
        addToWishlist: 'Добавлено в список желаний!',
        duplicateUrl: 'Эта ссылка уже есть в вашем списке желаний!',
        shareableLinkGenerated: 'Общая ссылка создана! Отправьте её другим.',
        wishlistOf: 'Список желаний:',
        noItemsYet: 'Пока нет товаров',
        confirmBooking: 'Подтвердить бронирование',
        yourNamePlaceholder: 'Ваше имя',
        welcomeMessage: 'Добро пожаловать в Birthday Wishlist!',
        welcomeDescription: 'Создайте личный список желаний и поделитесь им с друзьями и семьей.',
        createButton: 'Создать свой список желаний'
    },
    de: {
        title: 'Geburtstags-Wunschliste-Plattform',
        subtitle: 'Erstellen und teilen Sie Ihre Wunschliste mit Freunden und Familie!',
        createWishlist: 'Erstellen Sie Ihre Wunschliste',
        yourName: 'Ihr Name:',
        itemName: 'Artikelname:',
        itemLink: 'Artikellink (optional):',
        paste: 'Einfügen',
        price: 'Preis (optional):',
        addItem: 'Artikel hinzufügen',
        loadingProduct: 'Produktinformationen werden geladen...',
        yourCurrentWishlist: 'Ihre aktuelle Wunschliste',
        generateShareableLink: 'Freigabelink generieren',
        shareLinkText: 'Teilen Sie diesen Link mit anderen:',
        copy: 'Kopieren',
        copied: 'Kopiert!',
        totalBudget: 'Gesamtbudget',
        totalItems: 'Gesamtartikel',
        bookedItems: 'Gebuchte Artikel',
        availableItems: 'Verfügbare Artikel',
        viewWishlist: 'Wunschliste von jemandem ansehen',
        enterWishlistLink: 'Wunschlist-Link eingeben:',
        loadWishlist: 'Wunschliste laden',
        bookThisItem: 'Diesen Artikel buchen',
        bookItem: 'Artikel buchen',
        booked: 'Gebucht',
        bookedBy: 'Gebucht von:',
        viewItem: 'Artikel ansehen',
        addToWishlist: 'Zur Wunschliste hinzugefügt!',
        duplicateUrl: 'Diese URL ist bereits in Ihrer Wunschliste!',
        shareableLinkGenerated: 'Freigabelink generiert! Senden Sie ihn an andere.',
        wishlistOf: 'Wunschliste von:',
        noItemsYet: 'Noch keine Artikel',
        confirmBooking: 'Buchung bestätigen',
        yourNamePlaceholder: 'Ihr Name',
        welcomeMessage: 'Willkommen bei Birthday Wishlist!',
        welcomeDescription: 'Erstellen Sie Ihre persönliche Wunschliste und teilen Sie sie mit Freunden und Familie.',
        createButton: 'Erstellen Sie Ihre Wunschliste'
    }
};